Feature/composer install
WebDevStudios/wds-headless-wordpress pull request #2
Opened 2021-01-26 17:23 UTC by jrfoell

No issue to close here, just wanted you guys to see what my approach to all the plugin requirements would look like. It's a biggie b/c I deleted all of the plugins checked into your repo. _Actual_ changes are found int he composer.json file.

2021-01-26 18:10 UTC, oddevan commented on composer.json
> -    "webdevstudios/sso": "^2.0",
Does this remove `webdevstudios/sso` from the project? Do we need it?

2021-01-26 20:11 UTC, gregrickaby commented on composer.json
> +    "wpackagist-plugin/cookie-notice": "^1.3",
Don't need

2021-01-26 20:11 UTC, gregrickaby commented on composer.json
> +    "wp-media/wp-rocket": "^3.6",
Don't need

2021-01-28 20:44 UTC, jrfoell commented
@oddevan `webdevstudios/sso` isn't needed because requiring the WDS add-on `webdevstudios/sso-addon` brings in the _correct_ companion SSO version that goes with it.

2021-01-29 13:10 UTC, gregrickaby requested changes

2021-01-29 13:10 UTC, gregrickaby commented on composer.json
> -    "wp-graphql/wp-graphql-acf": "^0.4.0",
@jrfoell We need `wp-graphql-acf`, can you please add it back in.

2021-02-01 20:42 UTC, jrfoell commented
LOL, okay

![wp-graphql-acf-dont-need](https://user-images.githubusercontent.com/630830/106515752-bab40300-649b-11eb-8edb-59e5309fa64a.png)

I added `lazy-blocks` via composer as well

2021-02-01 21:04 UTC, merged